### ISSUE TITLE
Transmog removes set bonuses

### ISSUE THREAD

**Issue by NexusWoW** [azerothcore/mod-transmog#3] opened 2017-02-24 08:13 UTC
As title suggests, applying a transmog to an item makes its set bonus attributes not work. repeatable, simply have two items that create a 2 set bonus, and transmog one of the items.

**Comment by Yehonal** [comment] 2017-08-20 12:59
@Rochet2 have you ever had this issue with transmog system?

**Comment by Rochet2** [comment] 2017-08-20 16:34
Never confirmed to be true.
What actually happens is that tooltips dont show the set bonuses properly since we fake that we have another item equipped. People do not actually test if the bonus itself is applied, they just see in the tooltip the visual bug of set bonus not applying.
Even though the client says the set bonus is not active, the core still should properly handle applying the set bonus. This means that spells will proc and stats are there.

Please actually confirm with the stats and procs instead of relying on the tooltips.
If the stats are missing then it is an issue somewhere. Otherwise its just a visual bug in the tooltip system we cannot properly avoid without client side edits.

**Comment by BarbzYHOOL** [comment] 2018-02-27 21:49
What kind of client side edits?

**Comment by Deku** [comment] 2018-02-27 22:21
A quick check of the auras should show if the set bonus is applied or not

**Comment by Rochet2** [comment] 2018-02-27 22:43
> What kind of client side edits?

Let's say you make an addon. Transmog sets fake equipment. You can send real equipment through addon messages from the server to the addon and overwrite tooltips based on that.

**Comment by yimgame** [comment] 2018-12-27 01:06
U can see bonus are working on the item inside the bag.

https://youtu.be/RdzgLFHUGFQ

by the way, how to do an aura checking ?

**Comment by Rochet2** [comment] 2018-12-27 12:31
> by the way, how to do an aura checking ?

Try .list aura
it should list all auras on you.
Maybe before testing you should (on a test character, not real player) do .unaura all
this should remove all talent auras and such so the aura list will be smaller.

**Comment by arnaucastellvi** [comment] 2021-08-08 22:35
The reverse is also true.
Transmog activate the bonuses of the item you transmodify. 
![imatge](https://user-images.githubusercontent.com/26790128/128647619-0c8f5010-3062-4c1f-a423-fe730fe43510.png)

**Comment by dennots** [comment] 2022-04-06 18:16
If it's working as intented, why not explain this on the transmog NPC explanation dialogue? Instead of having players guessing

**Comment by Nyeriah** [comment] 2024-08-30 11:10
It's only a visual effect, caused by the fact we send a different item ID to the client in order to display the new appearance. I will be closing this, since this is not fixable without editing the client, and that's outside the scope of this module.

**Closed by Nyeriah** 2024-08-30 11:10 UTC
Labels: bug
